/*
 * This file is generated by jOOQ.
 */
package io.github.tkaczenko.koatuuparser.entity;


import io.github.tkaczenko.koatuuparser.entity.tables.Location;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.location</code>.
     */
    public static final Location LOCATION = io.github.tkaczenko.koatuuparser.entity.tables.Location.LOCATION;
}
